### ISSUE TITLE
Can't use node:path.sep in browser

### ISSUE THREAD

**Issue by Zehir** [alexgorbatchev/file-paths-to-tree#1]
Hello, I just found this lib and it's exactly what I needed but I cant use it directly because it's use the directory seperator from node and I would like to use it in a browser using Vite.

Is it's possible to remove the dependency of nodejs ?

Also it's may be possible that the path you parsing is not using the OS separator

I get this error message ; 
Module "node:path" has been externalized for browser compatibility. Cannot access "node:path.sep" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

Thanks

**Comment by alexgorbatchev** [comment]
Fixed
